Source/MvvmCross.Plugins.BLE.Droid/Bluetooth/LE/Adapter.cs
Manually parse out Manufacturer Specific Data from raw Advertising byte array when API < 21
=> Parse out Manufacturer Specific Data for API < 21

Source/MvvmCross.Plugins.BLE.Droid/Bluetooth/LE/Characteristic.cs
Fix bug on Characteristics#ReadAsync which enabled characteristics to get as result the values of other characteristics.
=> When reading make sure the result is set for the correct characteristic.

Source/Plugin.BLE.Android/Characteristic.cs
The [BLE GATT Descriptors spec](https://developer.bluetooth.org/gatt/descriptors/Pages/DescriptorsHomePage.aspx) defines a specific Descriptor that clients should use to write [Client Characteristic Configurations](https://developer.bluetooth.org/gatt/descriptors/Pages/DescriptorViewer.aspx?u=org.bluetooth.descriptor.gatt.client_characteristic_configuration.xml) such as enabling notifications or indications. Although it is sometimes (often) the first descriptor that appears in `_nativeCharacteristic.Descriptors`, order isn't guaranteed. For some devices (including the one I'm working with now), another descriptor comes first and grabbing the first one out of the list will result in never actually enabling notifications on the characteristic.
=> Use the Client Characteristic Configuration Descriptor instead of the first available Descriptor

Source/Plugin.BLE.iOS/Descriptor.cs
IDescriptor.ReadAsync() fails (i.e. it returns null) on iOS if the descriptor's value is a string. This commit fixes this by converting the NSString value to an UTF8-encoded byte-array.
=> Add support for NSString descriptor values

.gitignore, Source/BLE.Client/BLE.Client/ViewModels/DeviceListViewModel.cs, Source/Plugin.BLE.Abstractions/Contracts/IDevice.cs, Source/Plugin.BLE.Abstractions/DeviceBase.cs, Source/Plugin.BLE.Android/CallbackEventArgs/MtuRequestCallbackEventArgs.cs, Source/Plugin.BLE.Android/Device.cs, Source/Plugin.BLE.Android/GattCallback.cs, Source/Plugin.BLE.Android/Plugin.BLE.Android.csproj, Source/Plugin.BLE.iOS/Device.cs
Hi,
I added the possibility to request an MTU update for a peripheral. 
The requestMTU(int size) method can be called on an iDevice.  After calling it the function will return the new negotiated MTU (which can be differ from your requested one).
Feature Reason:
For iOS the bluetooth "Exchange MTU Request" will be called automatically after connection process. The MTU will be negotiated to about 158bytes for newer devices. Unfortunately on Android this is not done by itself..
There are a few restrictions:
Android < API 21: No such api available. An default value will be returned (-1)
iOS: Not possible to change MTU. The current negotiated MTU will be returned (CBPeripheral.GetMaximumWriteValueLength).
=> Added requestMTU feature (issue #128)

Source/BLE.Client/BLE.Client/ViewModels/DeviceListViewModel.cs, Source/Plugin.BLE.Abstractions/ConnectionInterval.cs, Source/Plugin.BLE.Abstractions/Contracts/IDevice.cs, Source/Plugin.BLE.Abstractions/DeviceBase.cs, Source/Plugin.BLE.Abstractions/Plugin.BLE.Abstractions.csproj, Source/Plugin.BLE.Android/Device.cs, Source/Plugin.BLE.iOS/Device.cs
Hi,
The Android BLE stack is able to define the connection priority (high, low, balanced) and therefore change the connection interval for a connection.
The connection interval influences the ble performance and battery consumption massively.
**Android Gatt Function:**
https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#requestConnectionPriority(int)
**Android Settings for Connection Priority:**
https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#CONNECTION_PRIORITY_BALANCED
Its not available on iOS so this function will only work for Android (and API Level >= 21).
On iOS the call will return TRUE. Why true? I think returning FALSE could lead to unexpected behaviour if somebody reacts on the return value in the consuming app.
Please …
=> Added possibility to change ConnectionPriority/ ConnectionInterval for Android

Source/Plugin.BLE.iOS/Device.cs
The handler function can be called for two reasons: 1) service discovery succeeded or 2) service discovery failed. In the later case `args.Error` will not be null and `_nativeDevice.Services` may be null. In that case, we cannot return from the handler without setting the result on the TaskCompletionSource. Doing so will certainly cause a deadlock because this task will never complete. The fact that the event handler is removed by `_nativeDevice.DiscoveredService -= handler;` ensures that. 
If an error occurs, the code will not complete with an empty list of services. Then the caller can do what they choose with that.
=> Fixed potential deadlock while discovering services

README.md, Source/Plugin.BLE.Android/Characteristic.cs, Source/Plugin.BLE.Android/GattCallback.cs
This is a fix for Android when reconnecting to a previously connected IDevice, any GATT operations would return FALSE because the services & characteristics cache is no longer valid.
I am simply calling DeviceBase.ClearServices() (as it is in iOS) when device is disconnected (lost or intentionnaly).
I've also merge my PR for Issue #227 into the 1.3.0 branch.
=> [Android] 1.3.0 - GATT operations issue on reconnecting on a previously connected IDevice

Source/BLE.Client/BLE.Client.iOS/Resources/LaunchScreen.storyboard
Set storyboard to iOS 7 and above, otherwise the ble.client.io project can't compile in VS for Mac.
=> Set storyboard to iOS 7 and above.

Source/Plugin.BLE.Android/Adapter.cs, Source/Plugin.BLE.Android/Device.cs
Application is registered for notifications when an autoconnected device comes into range. There is a maximum amount of registrations allowed simultaneously, and each connect creates a new registration:
```
I/mono-stdout(10118): $> Attempt connect (last attempt 4381ms ago)
D/BluetoothManager(10118): getConnectionState()
D/BluetoothManager(10118): getConnectedDevices
D/BtGatt.GattService( 1665): getDeviceType() - device=24:71:89:2B:3F:45, type=2
D/BluetoothGatt(10118): connect() - device: A0:E6:F8:88:C5:12, auto: true
D/BluetoothGatt(10118): registerApp()
D/BluetoothGatt(10118): registerApp() - UUID=dcc69ef2-65ae-4053-b909-a54da55a24f2
D/BtGatt.GattService( 1665): registerClient() - UUID=dcc69ef2-65ae-4053-b909-a54da55a24f2
D/BtGatt.GattService( 1665): onClientRegistered() - …
```
=> Fix #297 - Close created GATT when cancelling autoconnect requests

Source/Plugin.BLE.iOS/BleImplementation.cs
Fixes #129 
User can decide to enable or not the option `ShowPowerAlert` on iOS. When this option is enable, a message will be displayed to the user to turn On the bluetooth in the Settings when in airplane mode and bluetooth is Off. In our case, this message is annoying for our users.
Run the following within `AppDelegate.FinishedLaunching` before any other usage of the plugin: `BleImplementation.ShowPowerAlert(false);`.
Default value of `ShowPowerAlert` is true. The `ShowPowertAlert` will be display even if there is no options provided to `CBCentralManager` constructor.
=> Added an option to ShowPowerAlert for iOS.

Source/Plugin.BLE.Abstractions/DeviceBase.cs
Fixes collection was modified bug
```List`1+Enumerator[T].MoveNextRare ()
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.Linq
Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found)
System.Linq
Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate)
Plugin.BLE.Abstractions
DeviceBase+<GetServiceAsync>d__28.MoveNext ()
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification
```
=> Fix collection was modified; enumeration operation may not execute bug

Source/Plugin.BLE.Abstractions/AdapterBase.cs
_currentScanDeviceFilter is null, if the app starts over willRestoreState. 
If _currentScanDeviceFilter is null, than no filter is set and we can ignore it.
=> Fix possible nullpoint exception

README.md, Source/BLE.Client.UWP/BLE.Client.UWP.csproj, Source/BLE.Client.UWP/Package.appxmanifest, Source/BLE.Client/BLE.Client/ViewModels/DeviceListViewModel.cs, Source/Plugin.BLE.Abstractions/ConnectParameter.cs, Source/Plugin.BLE.Abstractions/Contracts/IAdapter.cs, Source/Plugin.BLE.UWP/Adapter.cs, Source/Plugin.BLE.UWP/BleImplementation.cs, Source/Plugin.BLE.UWP/Device.cs, Source/Plugin.BLE.UWP/Extensions/ScanModeExtension.cs, Source/Plugin.BLE.UWP/Plugin.BLE.UWP.csproj, Source/Plugin.BLE.UWP/Service.cs
During my test, ~~if `ScanningMode = BluetoothLEScanningMode.Active` I got no device scanned.
But if `ScanningMode = BluetoothLEScanningMode.Passive` (default value), I got device list same as the result of Android/iOS.~~
EDIT: I tested again the other day, the Thinkpad E450 can scan my devices at `Active` mode. 
Another example is from https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/BluetoothAdvertisement/cs/Scenario1_Watcher.xaml.cs and it uses the default (`Passive`) value.
=> [UWP]Use Adapter.ScanMode to set UWP's  ScanningMode

Source/BLE.Client/BLE.Client.Droid/BLE.Client.Droid.csproj, Source/BLE.Client/BLE.Client.Droid/Resources/Resource.Designer.cs, Source/BLE.Client/BLE.Client.iOS/BLE.Client.iOS.csproj, Source/BLE.Client/BLE.Client.macOS/BLE.Client.macOS.csproj, Source/BLE.Client/BLE.Client/BLE.Client.csproj, Source/BLE.Client/BLE.Client/ViewModels/CharacteristicDetailViewModel.cs, Source/BLE.Client/BLE.Client/ViewModels/DescriptorDetailViewModel.cs, Source/BLE.Client/BLE.Client/ViewModels/DescriptorListViewModel.cs, Source/BLE.Client/BLE.Client/ViewModels/DeviceListViewModel.cs, Source/BLE.Client/BLE.Client/ViewModels/ServiceListViewModel.cs, Source/MvvmCross.Plugins.BLE.macOS/Plugin.cs
Suppressed a few warnings across the solution.
Updated Xamarin.Forms to version 4.2.
Fixed an issue with the error toast being displayed for too long.
=> Suppressed a few warnings across the solution.

Source/Plugin.BLE.iOS/Device.cs
Does GetServiceAsync() correctly works only if called after GetServicesAsync() on iOS 13?
=> fixed #396

Source/Plugin.BLE.Android/Adapter.cs, Source/Plugin.BLE.Android/Plugin.BLE.Android.csproj
* by default only legacy advertisements (4.2 and below) are detected
* see https://developer.android.com/reference/android/bluetooth/le/ScanSettings.Builder#setLegacy(boolean)
* the target framework version needs to be increased to 8.0 for this
=> Plugin.BLE.Android: enable BT 5 advertising extensions (#495)

README.md, Source/BLE.Client/BLE.Client.iOS/Info.plist, Source/BLE.Client/BLE.Client.macOS/Info.plist
... and mention in the README that it's required on Mac OS Big Sur.
This fixes #498 and #455.
=> Use NSBluetoothAlwaysUsageDescription in iOS and macOS samples

Source/Plugin.BLE.Android/Device.cs
The gatt handles are leaking otherwise, resulting in too many open
handles. Android will block further attempts if an app has 32 open
gatts.
Closes #484
=> Correctly closes a gatt when a connection attempt is cancelled+

.build/MvvmCross.Plugin.BLE.nuspec, .build/build.cake, .github/workflows/dotnet.yml, Source/Plugin.BLE.Android/Plugin.BLE.Android.csproj
This fixes the github actions build (via cake), and removes some warnings and errors. Most be the problems were caused by the windows-latest environment having switched to [Windows2022](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md), apparently.
It originally failed with `MSBuild: Could not locate executable.`, but the were a couple more issues and warnings. E.g. we got a `XA5207: Could not find android.jar for API level 26`, because the Windows 2022 environment only includes Android SDK v27 and higher.
=> Fix github actions

Source/Plugin.BLE.Android/Adapter.cs, Source/Plugin.BLE.Android/Device.cs, Source/Plugin.BLE.Android/GattCallback.cs
Resolves #182 
Basically only closes the gatt instance when autoConnect was set to false when connecting to that device
=> Fix Android autoConnect flag

Source/Plugin.BLE.Abstractions/AdapterBase.cs, Source/Plugin.BLE.Abstractions/Contracts/IAdapter.cs, Source/Plugin.BLE.Abstractions/Utils/FakeAdapter.cs, Source/Plugin.BLE.Android/Adapter.cs, Source/Plugin.BLE.iOS/Adapter.cs
Such a method was missing for iOS as `GetSystemConnectedOrPairedDevices` returned only the currently connected devices. Androids `GetSystemConnectedOrPairedDevices` works just fine.
Introduces a new method to introduce no breaking change for `GetSystemConnectedOrPairedDevices` on iOS, if that method would start to return non-connected, paired devices too.
=> Adds GetKnownDevicesByIds-Method to get paired devices without the need of connecting to them

.build/build.cake, .github/workflows/dotnet.yml, Source/Plugin.BLE.Tests/Plugin.BLE.Tests.csproj
This extends the GHA config to build & run the unit tests. As a preparation, the test project is updated to .NET 5 and the cake script is extended to support the unit test. GHA runs the corresponding cake targets in the end. Fixes #583.
=> GitHub Actions: run tests

Source/BLE.Client/BLE.Client.Droid/BLE.Client.Droid.csproj, Source/BLE.Client/BLE.Client.Droid/Helpers/PlatformHelpers.cs, Source/BLE.Client/BLE.Client.Droid/Properties/AndroidManifest.xml, Source/BLE.Client/BLE.Client.iOS/BLE.Client.iOS.csproj, Source/BLE.Client/BLE.Client.iOS/Helpers/PlatformHelpers.cs, Source/BLE.Client/BLE.Client.macOS/BLE.Client.macOS.csproj, Source/BLE.Client/BLE.Client.macOS/Helpers/PlatformHelpers.cs, Source/BLE.Client/BLE.Client/BLE.Client.csproj, Source/BLE.Client/BLE.Client/Helpers/IPlatformHelpers.cs, Source/BLE.Client/BLE.Client/ViewModels/DeviceListViewModel.cs
This updates the target framework version to 12 for BLE.Client.Droid, uses the new Bluetooth permission scheme and adds the necessary runtime handling for the new Bluetooth permissions (while keeping backward compatibility to older Android versions). I tested it on Android 11 and 12, and verified that the sample app sees BLE advertisements on both versions.
It is proof that the library works well with Android 12 (without any changes necessary) and only proper permission handling is needed in client apps. It also provide a blueprint of how to handle the new permissions.
Furthermore it removes the requirement for the location permission on Android 12, and thereby fixes #568. It also relates to #579.
The runtime permission handling is inspired by @jamesmontemagno's sketch in …
=> BLE.Client: update to Android12

Source/BLE.Client/BLE.Client/ViewModels/DeviceListViewModel.cs, Source/Plugin.BLE.Abstractions/AdapterBase.cs, Source/Plugin.BLE.Abstractions/Contracts/IAdapter.cs, Source/Plugin.BLE.Abstractions/Extensions/AdapterExtension.cs, Source/Plugin.BLE.Abstractions/Extensions/AdapterExtenstion.cs, Source/Plugin.BLE.Abstractions/ScanFilterOptions.cs, Source/Plugin.BLE.Android/Adapter.cs
This is a follow-up to @AdamDiament's #578. It further extends the scan-filtering capabilities (on Android) with the option to filter on service data.
It also fixes a problem with the overloading of `IAdapter.StartScanningForDevicesAsync` that was introduced in #578 as well as a long-standing typo in a class name in one of the extension classes.
=> Scan filtering on service data, manufacturer data or device name

Source/BLE.Client/BLE.Client/ViewModels/DeviceListViewModel.cs, Source/Plugin.BLE.UWP/Adapter.cs
In Adapter.cs, if StartScanningForDevicesNativeAsync is called without specifying ScanFilterOptions (via the IAdapter overload which takes no parameters), then the lack of a null-check causes a crash.
In DeviceListViewModel.cs, I had previously submitted a pull request to add a null-check which had been accepted (commit 2317429f8a5e7153c00e090e9a66ccb3f49e4ad0), but it used the old-style syntax for null-guarding. This pull request updates it to the new C# syntax for null-guarding.
=> Added null-check to StartScanningForDevicesNativeAsync

Source/Plugin.BLE.Abstractions/DeviceBase.cs, Source/Plugin.BLE.UWP/Device.cs
Revised null handling that returns an empty list from GetServicesNativeAsync() in order to match the way that the Android code handles errors in GetServicesNativeAsync()
=> Added null-checks

Source/BLE.Client/BLE.Client.Droid/BLE.Client.Droid.csproj, Source/BLE.Client/BLE.Client.UWP/BLE.Client.UWP.csproj, Source/BLE.Client/BLE.Client.UWP/Helpers/PlatformHelpers.cs, Source/BLE.Client/BLE.Client.iOS/BLE.Client.iOS.csproj, Source/BLE.Client/BLE.Client.macOS/BLE.Client.macOS.csproj, Source/BLE.Client/BLE.Client/BLE.Client.csproj
UWP support in Acr.UserDialogs broke after version 7.1.0.514. And since the project is now abandoned and there is no way to open an issue, I don't know if we can get this fixed. If I create a brand-new empty UWP project and add a NuGet reference to the latest ACR.UserDialogs, I get the same bait library error. Maybe we could email or message the author, Allan Richie (@aritchie).
As a temporary fix until we can figure out the correct fix, I've rolled back the version of Acr.UserDialogs to 7.1.0.514
Visual Studio automatically removed the <ItemGroup> references to the folder 'Helpers', apparently because since the C# file in that folder was referenced directly in the project, the folder reference is superfluous. In any case, the folder still shows up in all the non-UWP projects (where it is …
=> Fix for Acr.UserDialogs bait library problem

Source/Plugin.BLE.Android/Characteristic.cs, Source/Plugin.BLE.Android/GattCallback.cs
In our application the value received by an update/notification is not the same as the value read.
So in some cases while we´re doing a read we receive an update and both returns the notification value.
We previously used cordova-plugin-ble-central and they seems to handle reads and notifications differently.
=> Dont use same event handler for notifications as for read

.github/workflows/dotnet.yml, Source/Plugin.BLE.Tests/Plugin.BLE.Tests.csproj
Since .NET 5 is out of support by now, I'm updating Plugin.BLE.Tests to .NET 6, use .NET 6 also in the Github Actions setup and update some packages in the Tests project while I'm at it.
=> Update Tests to .NET 6

Source/BLE.Client/BLE.Client.UWP/BLE.Client.UWP.csproj, Source/Plugin.BLE/Plugin.BLE.csproj, Source/Plugin.BLE/Windows/Adapter.cs, Source/Plugin.BLE/Windows/Device.cs
This PR does a couple of things:
* It updates Microsoft.Toolkit.Uwp.Connectivity from 6.1 to 7.1 (for the Xamarin.UWP case, for MAUI on Windows we already have CommunityToolkit.WinUI.Connectivity v7.1).
* It updates the minimum target platform version for Xamarin.UWP to 10.0.17763 (which is necessary for the above Toolkit version and matches what we already have for MAUI).
* It fixes the NullReferenceException from #356 by obtaining the DispatcherQueue on the UI thread.
* It also updates BLE.Client.UWP a bit.
I verified with BLE.Client.UWP that scanning on Windows works well, and I strongly assume that things should also work with MAUI now (this still needs confirmation, though).
=> Fix problems with MAUI on Windows

Source/Plugin.BLE/Android/Adapter.cs, Source/Plugin.BLE/Apple/Adapter.cs, Source/Plugin.BLE/Shared/AdapterBase.cs, Source/Plugin.BLE/Shared/Contracts/IAdapter.cs
This PR implements the major parts of issue #675, adding two new methods to the IAdapter interface:
* `supportsExtendedAdvertising`
* `supportsCodedPHY`
The first one has implementations on Android and iOS (and returns false on other platforms, such as MacOS and Windows), the second one is implemented only on Android.
=> Querying adapter capabilities: extended advertisements & coded phy

.github/workflows/dotnet.yml, Source/BLE.Mac.slnf, Source/MvvmCross.Plugins.BLE/MvvmCross.Plugins.BLE.csproj, Source/Plugin.BLE/Plugin.BLE.csproj
This should fix #683, essentially by building only the MAUI parts on Mac, but not the Xamarin parts, since mixed Xamarin/MAUI builds seem to be broken on Mac.
Furthermore I'm adding a Mac build to the Gihub Actions CI, which verifies that building on Mac works (at least the core libs).
=> Fix build on Mac

Source/Plugin.BLE/Windows/Adapter.cs, Source/Plugin.BLE/Windows/Device.cs
Fixes problems with connecting and disconnecting on Windows:
1) DisconnectDeviceAsync hangs and device remains connected
2) When a connected device loses power, DeviceDisconnected is fired instead of DeviceConnectionLost
Steps to reproduce 1 of 2:
1) Start App
2) Power On Device
3) Start Scanner
4) Select Device
5) Stop Scanner
6) Connect to device
7) Power off device
* Error: DeviceDisconnected is fired instead of DeviceConnectionLost
8) Power On Device
9) Connect to device
10 Disconnect device
* Error: Disconnect hangs and device remains connected
Steps to reproduce 2 of 2:
1) Start App
2) Power On Device
3) Start Scanner
4) Select Device
5) Stop Scanner
6) Power off device
* Error: DeviceDisconnected is fired instead of DeviceConnectionLost
7) Connect to device
* Correct: Device …
=> Fix windows connect/disconnect issues #528, #536, #423. #620

.build/build.cake, .github/workflows/dotnet.yml
... by downgrading the .NET SDK from 7.0.400 to 7.0.30x.
This fixes the CI failures seen in all recents PRs (e.g. #730, #735, #736). Since I found no other way to fix the errors, this is my last resort (and should only be a temporary measure).
The failures appeared when the SDK version on the build host was upgraded to 7.0.400. I still don't fully understand the problem. It might possibly be a bug in the 7.0.400 tooling (or at least a change in behavior).
Other things that I have tried (but did not help):
* getting rid of cake
* removing the net6.0 targets
=> Fix GHA failures

Source/BLE.Client/BLE.Client.Droid/BLE.Client.Droid.csproj, Source/BLE.Client/BLE.Client.Droid/Properties/AndroidManifest.xml, Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj, Source/MvvmCross.Plugins.BLE/MvvmCross.Plugins.BLE.csproj, Source/Plugin.BLE/Plugin.BLE.csproj
This is motivated by #730, which makes use of Android API level 33. We now target Android 13 (SDK level 33) everywhere.
For the libs (Plugin.BLE and MvvmCross.Plugins.BLE):
* With Xamarin.Android, we update the Android target framework from 10 to 13.
* For .NET 6 and 7, we explicitly target Android 33 now (.NET 7 already had it, but .NET 6 only had 31).
For the samples:
* BLE.Client.Droid: Update the the target framework version from 12 to 13.
* BLE.Client.Maui: Explicitly target Android 33 with .NET 7 (effectively no change).
=> Target Android 13 everywhere

Source/MvvmCross.Plugins.BLE/MvvmCross.Plugins.BLE.csproj, Source/Plugin.BLE/Plugin.BLE.csproj
Rationale:
* .NET 6 Maui (including the Android, iOS and Maccatalyst targets) is not supported any more, which generates lots of warnings in our builds.
* .NET 6 in general (with the Windows target) is still supported for another year in principle. But since Plugin.BLE is a cross-platform library, I see little incentive for keeping the Windows target of .NET 6 only.
* Of course the .NET 7 targets continue to be available, and .NET 8 will be added soon.
References:
* https://dotnet.microsoft.com/en-us/platform/support/policy/maui
* https://dotnet.microsoft.com/en-us/platform/support/policy
=> Remove .NET 6

Source/BLE.Client/BLE.Client.WinConsole/BleDemo.cs, Source/BLE.Client/BLE.Client.WinConsole/ConsoleTracer.cs, Source/BLE.Client/BLE.Client.WinConsole/Program.cs, Source/Plugin.BLE/Windows/Adapter.cs, Source/Plugin.BLE/Windows/Device.cs
In the Windows implementation, the ConnectToDeviceNativeAsync method did not work properly.
It was especially seen in the case when:
1. Connect
2. Get services
3. Disconnect
4. Connect
5. Get services
This has now been solved
=> Improve Connect In Windows

.github/workflows/dotnet.yml, Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj, Source/MvvmCross.Plugins.BLE/MvvmCross.Plugins.BLE.csproj, Source/Plugin.BLE/Plugin.BLE.csproj
This PR adds a Linux build to the GitHub Actions config and disables the iOS and Mac targets when building on a Linux host, so that the libs and the sample app can be built on Linux successfully (but with the Android target only).
=> GHA: add a Linux build

Source/Plugin.BLE/Android/BleImplementation.cs, Source/Plugin.BLE/Apple/BleImplementation.cs, Source/Plugin.BLE/Shared/BleImplementationBase.cs, Source/Plugin.BLE/Shared/Contracts/IBluetoothLE.cs, Source/Plugin.BLE/Windows/BleImplementation.cs
In the Windows Implementation I have added a `TrySetStateAsync`.
It works nicely in the Windows tool I have, but I guess security stuff doesn't allow this for Android + iOS, so I find no need to extend the interface,
but it is nice that the Windows implementation reuse the radio instance.
=> Turn Bluetooth Radio On/Off

.build/build.cake, Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj
I recently noticed that a couple of our sample clients are not yet inlcuded in the cake build script and therefore not built on Windows via GHA. Some of them I have already added on master, missing at this point is only BLE.Client.Maui, which is added by the PR. However, the Windows build currently fails (on the net8.0-windows target) with this error, which I don't quite understand:
```
Unable to optimize assemblies for performance: a valid runtime package was not found.
Either set the PublishReadyToRun property to false, or use a supported runtime identifier when publishing.
When targeting .NET 6 or higher, make sure to restore packages with the PublishReadyToRun property set to true.
```
I'm not even sure why anything is supposed to be 'published' here, because we actually just want to …
=> GHA: build Maui client on Windows

Source/Plugin.BLE/Android/BleImplementation.cs, Source/Plugin.BLE/Shared/Contracts/IBluetoothLE.cs
This implements the only method that works beyond API level 32. However, it only really covers the enable part, not the disabling. Fixes issue #821.
=> Implement BleImplementation.TrySetStateAsync on Android

Source/Plugin.BLE/Apple/Characteristic.cs
This is supposed to fix a small bug on iOS, see #825.
=> Fix a NullReferenceException in Characteristic.NSErrorToGattStatus

Source/BLE.Client/BLE.Client.WinConsole/PluginDemos.cs, Source/BLE.Client/BLE.Client.WinConsole/WindowsDemos.cs, Source/Plugin.BLE/Plugin.BLE.csproj, Source/Plugin.BLE/Shared/DeviceState.cs, Source/Plugin.BLE/Windows/Adapter.cs, Source/Plugin.BLE/Windows/Device.cs
This change allows the connect sequence to be established even though the device is already connected.
An already connection could be due to pairing, which connects the device.
@janusw: This ended up with a simple solution :-)
If merging this new simple PR, we can discard the old one, which I have now closed... (https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/pull/818)
=> Windows: Handle that a device is already connected

Source/Plugin.BLE/Shared/Contracts/IDevice.cs, Source/Plugin.BLE/Windows/Device.cs
* updating the RSSI is currently not supported on Windows, therefore the method should return a false value
* also: update the documentation and fix some typos
* this fixes #810
=> fix Device.UpdateRssiAsync on Windows

Source/Plugin.BLE/Windows/Adapter.cs, Source/Plugin.BLE/Windows/BleImplementation.cs
=> Implement Adapter.SupportsExtendedAdvertising on Windows

Source/Plugin.BLE/Windows/Adapter.cs
To fix https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/828
=> Windows: Fixed null entries in DiscoveredDevices  #828

Source/BLE.Client/BLE.Client.WinConsole/PluginDemos.cs, Source/BLE.Client/BLE.Client.WinConsole/Program.cs, Source/BLE.Client/BLE.Client.WinConsole/WindowsDemos.cs, Source/Plugin.BLE/Windows/Adapter.cs
To fix: https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/826
[demolog.txt](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/files/15251792/demolog.txt)
=> Windows: Connect -> ConnectionLost -> Reconnect

Source/BLE.Client/BLE.Client.WinConsole/PluginDemos.cs, Source/Plugin.BLE/Windows/Characteristic.cs
=> Fixed StartUpdatesNativeAsync for indicate

.github/workflows/dotnet.yml
... in order to fix the build errors observed in #880, see https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/pull/880#issuecomment-2280301790.
=> GHA: update to MacOS 14

.github/workflows/dotnet.yml
This fixes the recent GHA build errors on Mac by updating to MacOS 15 and XCode 16 (which is required with the latest .NET 8 SDK now).
=> GHA: update to MacOS 15 and XCode 16

Source/Plugin.BLE/Windows/Adapter.cs
`PairAsync ` didn't work for Windows.
See [stack overflow](https://stackoverflow.com/questions/45191412/deviceinformation-pairasync-not-working-in-wpf)
* Added CustomPairing
* added default case to PairingHandler for error traceing
=> Added CustomPairing for Windows

Source/Plugin.BLE/Apple/Characteristic.cs
The Characteristics.WriteNativeAsync method was not recognizing the cancellation token in mode WriteWithoutResponse on iOS (forget this in my last pull request).
=> provide missing cancellation token to write characteristics method
