- Source/BLE.Client.Droid/BLE.Client.Droid.csproj
- Source/BLE.Client.Droid/packages.config
- Source/MvvmCross.Plugins.BLE.Droid/Bluetooth/LE/Characteristic.cs
- Source/MvvmCross.Plugins.BLE.Droid/MvvmCross.Plugins.BLE.Droid.csproj
- Source/MvvmCross.Plugins.BLE.Droid/packages.config
- Source/MvvmCross.Plugins.BLE.Touch/Bluetooth/LE/Adapter.cs
- Source/MvvmCross.Plugins.BLE.Touch/Bluetooth/LE/Characteristic.cs
- Source/MvvmCross.Plugins.BLE.Touch/Bluetooth/LE/Descriptor.cs
- Source/MvvmCross.Plugins.BLE.Touch/Bluetooth/LE/Device.cs
- Source/MvvmCross.Plugins.BLE.Touch/Bluetooth/LE/Extensions.cs
- Source/MvvmCross.Plugins.BLE.Touch/Bluetooth/LE/Service.cs
- Source/MvvmCross.Plugins.BLE.Touch/BluetoothLEManager.cs
- Source/MvvmCross.Plugins.BLE.Touch/MvvmCross.Plugins.BLE.Touch.csproj
- Source/MvvmCross.Plugins.BLE.Touch/Plugin.cs
- Source/MvvmCross.Plugins.BLE.Touch/packages.config
- Source/MvvmCross.Plugins.BLE/Bluetooth/LE/DeviceBase.cs
- Source/MvvmCross.Plugins.BLE/MvvmCross.Plugins.BLE.csproj
- Source/MvvmCross.Plugins.BLE/packages.config
Cleaned up the Touch version of the BLE plugin.
> BLE.Touch cleanup

- nuspec/MvvmCross.Plugin.BLE.nuspec
Plugin is not discoverable when searching Nuget for Bluetooth.
> Updated Nuget tags

- Source/Plugin.BLE.iOS/Adapter.cs
TxPower is now parsed from advertising data for iOS.
> TxPower is now parsed from advertising data for iOS

- Source/Plugin.BLE.Android/Characteristic.cs
Take two which correct formatting
> Fix Issue #227

- Source/BLE.sln
- Source/Plugin.BLE.UWP/Adapter.cs
- Source/Plugin.BLE.UWP/BleImplementation.cs
- Source/Plugin.BLE.UWP/Characteristic.cs
- Source/Plugin.BLE.UWP/CrossBluetoothLE.cs
- Source/Plugin.BLE.UWP/DefaultTrace.cs
- Source/Plugin.BLE.UWP/Descriptor.cs
- Source/Plugin.BLE.UWP/Device.cs
- Source/Plugin.BLE.UWP/Plugin.BLE.UWP.csproj
- Source/Plugin.BLE.UWP/Properties/AssemblyInfo.cs
- Source/Plugin.BLE.UWP/Properties/Plugin.BLE.UWP.rd.xml
- Source/Plugin.BLE.UWP/Service.cs
Full functionality of Plugin.UWP including connect, scan, get services/descriptors/characteristics, read and write characteristics/descriptors, event handlers, accessor methods, etc. I apologize for the lack of commits, I am new to git and was working completely locally for the great majority of the project :)
Known Issues for UWP:
-Disconnect cannot be implemented with UWP API
-GetSystemConnectedOrPairedDevices cannot be implemented without being async
-GetInitialState only returns connected or disconnected (also due to UWP API limitations)
-RequestMtu is not supported in windows
-Rssi cannot be updated since Rssi information is only recieved in nativeadvertisements
-UpdateConnectionInterval is not supported in UWP
-IsPrimary returns true as default since the method to get parent …
> Windows implemented

- README.md
- Source/BLE.Client.UWP/BLE.Client.UWP.csproj
- Source/BLE.Client.UWP/Package.appxmanifest
- Source/BLE.Client/BLE.Client/ViewModels/DeviceListViewModel.cs
- Source/Plugin.BLE.Abstractions/ConnectParameter.cs
- Source/Plugin.BLE.Abstractions/Contracts/IAdapter.cs
- Source/Plugin.BLE.UWP/Adapter.cs
- Source/Plugin.BLE.UWP/BleImplementation.cs
- Source/Plugin.BLE.UWP/Device.cs
- Source/Plugin.BLE.UWP/Plugin.BLE.UWP.csproj
- Source/Plugin.BLE.UWP/Service.cs
I submitted these pull requests to flyingxu's fork and he accepted them, but said that it would be better if I submitted them directly to the base repository
> Typos / Null check / Library updates / Fixed connection status events

- Source/Plugin.BLE.iOS/Adapter.cs
> Fixed the issue of empty NSData ToArray()

- Source/BLE.Client/BLE.Client.iOS/BLE.Client.iOS.csproj
- Source/BLE.Client/BLE.Client.iOS/Info.plist
- Source/Plugin.BLE.Android/Adapter.cs
- Source/Plugin.BLE.Android/Device.cs
- Source/Plugin.BLE.Android/GattCallback.cs
- Source/Plugin.BLE.iOS/Adapter.cs
- Source/Plugin.BLE.iOS/Characteristic.cs
- Source/Plugin.BLE.iOS/Descriptor.cs
- Source/Plugin.BLE.iOS/Device.cs
- Source/Plugin.BLE.iOS/Service.cs
Changes on BLE.Client.iOS.csproj are xamarin related and documented here: https://bugzilla.xamarin.com/show_bug.cgi?id=56734#c24
> Fix issue #280

- Source/BLE.Client/BLE.Client.Droid/BLE.Client.Droid.csproj
- Source/BLE.Client/BLE.Client.Droid/Properties/AndroidManifest.xml
- Source/BLE.Client/BLE.Client.Droid/Resources/Resource.Designer.cs
- Source/BLE.Client/BLE.Client.Droid/Resources/values/SplashStyle.xml
- Source/BLE.Client/BLE.Client.Droid/SplashScreen.cs
- Source/BLE.Client/BLE.Client.iOS/BLE.Client.iOS.csproj
- Source/BLE.Client/BLE.Client.iOS/packages.config
- Source/BLE.Client/BLE.Client/BLE.Client.csproj
- Source/BLE.Client/BLE.Client/BleMvxApplication.cs
- Source/MvvmCross.Plugins.BLE.Droid/MvvmCross.Plugins.BLE.Droid.csproj
- Source/MvvmCross.Plugins.BLE.Droid/packages.config
- Source/MvvmCross.Plugins.BLE.iOS/MvvmCross.Plugins.BLE.iOS.csproj
- Source/MvvmCross.Plugins.BLE.iOS/packages.config
Upgrade to Xamarin.Forms 3.2, 
Upgrade to MvvmCross 6.2.1,
Other nuget packages are also updated.
> Upgrade to Xamarin.Forms 3.2 and MvvmCross 6.2.1

- README.md
I just add some general information in README.md that were needed for me in order to be able to use this library on iOS.
> Update readme with iOS project setup.

- README.md
- Source/BLE.Client/BLE.Client/BLE.Client.csproj
- Source/MvvmCross.Plugins.BLE.Droid/MvvmCross.Plugins.BLE.Droid.csproj
- Source/MvvmCross.Plugins.BLE.iOS/MvvmCross.Plugins.BLE.iOS.csproj
- Source/Plugin.BLE.Abstractions/DeviceBase.cs
Hello,
this error i got : Unhandled Exception:
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
The App- Icon is show.
After (tested on single stepp) this (MainApplication.cs):
public void OnActivityResumed(Activity activity)
{
**CrossCurrentActivity.Current.Activity = activity;**
}
"CrossCurrentActivity.Current.Activity = activity;"  works (activity has value:"{md5284d34c42aded56ab4276d9b253081c8.SplashScreen@7e07a0f}")
After "NExt Stepp" on "}" i got the error.
But i tested on Emulator with Android 7, 8 and also on Device with Android 9
All the same issue
Output:
03-24 22:35:47.065 D/Mono    (24630): Assembly Ref addref MvvmCross.Binding.Droid[0x72297dbf80] -> MvvmCross.Platform.Droid[0x721d47c680]: 3
03-24 …
> On App start with visual studio, got only a error

- .build/build.cake
This is a shot in the dark, as I've no clue about the build tools :)
Fixes #367
> Actually build Plugin.BLE

- Source/Plugin.BLE.iOS/Adapter.cs
> Added iOS/Mac support for 32-bit and 16-bit Service UUIDs

- Source/Plugin.BLE.macOS/Plugin.BLE.macOS.csproj
Fixes #430 
Updated the output of assembly of MacOS to match filename of other platforms
> Updated Mac project to output the same filename as the other platforms

- .build/build.cake
- README.md
This PR fixes the problems reported in #492. In particular it updates the build instructions in the ReadMe file and fixes the cake build.
> Fix cake build and update build instructions

- .build/build.cake
- .github/workflows/dotnet.yml
Build the sample projects (BLE.Client.*) in addition to the core libraries. Also split off the 'Clean' and 'Restore' parts into separate steps.
> Extend the cake script and GH Actions build

- Source/BLE.Client/BLE.Client.Droid/MainActivity.cs
- Source/BLE.Client/BLE.Client.Droid/Setup.cs
- Source/BLE.Client/BLE.Client.iOS/Setup.cs
- Source/BLE.Client/BLE.Client.macOS/Setup.cs
- Source/BLE.Client/BLE.Client/BLE.Client.csproj
- Source/BLE.Client/BLE.Client/ViewModels/DeviceListViewModel.cs
* this fixes the runtime permission request on Android (#573)
> BLE.Client: replace Plugin.Permissions by Xamarin.Essentials.Permissions

- Source/BLE.Client/BLE.Client.Droid/BLE.Client.Droid.csproj
- Source/BLE.Client/BLE.Client.iOS/BLE.Client.iOS.csproj
- Source/BLE.Client/BLE.Client.macOS/BLE.Client.macOS.csproj
- Source/BLE.Client/BLE.Client/BLE.Client.csproj
> Some package updates

- Source/Plugin.BLE.iOS/Characteristic.cs
This pull requests allows to make unack writes on iOS
> Adding unacknowledge writes to iOS (#473)

- Source/MvvmCross.Plugins.BLE.UWP/MvvmCross.Plugins.BLE.UWP.csproj
- Source/Plugin.BLE.UWP/Adapter.cs
- Source/Plugin.BLE.UWP/Plugin.BLE.UWP.csproj
similar to #496, but for UWP instead of Android
> UWP: update target platform version and allow extended advertisements

- Source/Plugin.BLE.Abstractions/AdapterBase.cs
- Source/Plugin.BLE.Abstractions/Contracts/IAdapter.cs
- Source/Plugin.BLE.Abstractions/Contracts/ScanMatchMode.cs
- Source/Plugin.BLE.Android/Adapter.cs
- Source/Plugin.BLE.Android/Extensions/ScanMatchModeExtension.cs
- Source/Plugin.BLE.Android/Plugin.BLE.Android.csproj
This is a cleaned-up version of #606, where everything is squashed into one commit (and all unnecessary parts are removed).
@Bodwad, could you please double-check this, to make sure it is still working as intended and I did not mess up anything?
> Added Scan Match Mode to Android

- Source/BLE.Client/BLE.Client.Droid/BLE.Client.Droid.csproj
- Source/BLE.Client/BLE.Client.UWP/BLE.Client.UWP.csproj
- Source/BLE.Client/BLE.Client.iOS/BLE.Client.iOS.csproj
- Source/BLE.Client/BLE.Client.macOS/BLE.Client.macOS.csproj
- Source/BLE.Client/BLE.Client/BLE.Client.csproj
- Source/BLE.sln
minor updates of Xamarin.Forms and Xamarin.Essentials
> Package updates in BLE.Client

- Source/MvvmCross.Plugins.BLE.UWP/MvvmCross.Plugins.BLE.UWP.csproj
- Source/MvvmCross.Plugins.BLE.UWP/Plugin.cs
Added support for MVVMCross and UWP
> updated UWP plugin to support mvvmcross 8.

- Source/BLE.Client/BLE.Client/ViewModels/DescriptorListViewModel.cs
- Source/BLE.Client/BLE.Client/ViewModels/DeviceListViewModel.cs
- Source/Plugin.BLE.Tests/CharacteristicBaseTests.cs
- Source/Plugin.BLE/Android/Adapter.cs
- Source/Plugin.BLE/Android/BroadcastReceivers/BluetoothStatusBroadcastReceiver.cs
- Source/Plugin.BLE/Android/Device.cs
- Source/Plugin.BLE/Android/Extensions/ScanMatchModeExtension.cs
- Source/Plugin.BLE/Android/GattCallback.cs
- Source/Plugin.BLE/Android/Service.cs
- Source/Plugin.BLE/Apple/Adapter.cs
- Source/Plugin.BLE/Apple/BleCentralManagerDelegate.cs
- Source/Plugin.BLE/Apple/Characteristic.cs
- Source/Plugin.BLE/Apple/Descriptor.cs
- Source/Plugin.BLE/Apple/Service.cs
- Source/Plugin.BLE/Shared/AdapterBase.cs
- Source/Plugin.BLE/Shared/CharacteristicWriteType.cs
- Source/Plugin.BLE/Shared/ConnectionInterval.cs
- Source/Plugin.BLE/Shared/Contracts/IAdapter.cs
- Source/Plugin.BLE/Shared/Contracts/ICharacteristic.cs
- Source/Plugin.BLE/Shared/Contracts/IDevice.cs
- Source/Plugin.BLE/Shared/Extensions/AdapterExtension.cs
This fixes #693 (and some whitespace issues).
> Coding style fixes

- Source/Plugin.BLE/Android/Device.cs
fix for https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/713
and https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/567
> Fixed crash with incorrect data in advertisement data on android

- Source/Plugin.BLE/Shared/AdapterBase.cs
- Source/Plugin.BLE/Shared/Utils/TaskBuilder.cs
This is an attempt to fix #757. @skha83, could you please try this and tell me if it fixes the problem for you?
> disable MainThreadInvoker in Adapter.ConnectToDeviceAsync

- Source/Plugin.BLE/Windows/BleImplementation.cs
Implemented StateChanged for Windows
> StateChanged for Windows

- Source/BLE.Client/BLE.Client.WinConsole/BLE.Client.WinConsole.csproj
- Source/BLE.Client/BLE.Client.WinConsole/ConsoleTracer.cs
- Source/BLE.Client/BLE.Client.WinConsole/Demo.cs
- Source/BLE.Client/BLE.Client.WinConsole/PluginDemos.cs
- Source/BLE.Client/BLE.Client.WinConsole/Program.cs
- Source/BLE.Client/BLE.Client.WinConsole/WindowsDemos.cs
- Source/Plugin.BLE/Android/Device.cs
- Source/Plugin.BLE/Apple/Device.cs
- Source/Plugin.BLE/Plugin.BLE.csproj
- Source/Plugin.BLE/Shared/ConnectParameter.cs
- Source/Plugin.BLE/Shared/ConnectionParameterSet.cs
- Source/Plugin.BLE/Shared/Contracts/IDevice.cs
- Source/Plugin.BLE/Shared/DeviceBase.cs
- Source/Plugin.BLE/Windows/Adapter.cs
- Source/Plugin.BLE/Windows/BleImplementation.cs
- Source/Plugin.BLE/Windows/Device.cs
We need this in order to implement firmware update on devices.
https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothlepreferredconnectionparameters
> Connection parameters for windows

- Source/BLE.Client/BLE.Client.WinConsole/PluginDemos.cs
- Source/BLE.Client/BLE.Client.WinConsole/Program.cs
- Source/Plugin.BLE/Windows/Adapter.cs
Reproduce the error:
1. Connect
2. ConnectLost
3. Connect
Thereafter ConnectionChanged event was fired twice subsequently
@janusw : Yet another small PR for the Windows stability
> Fix ConnectionLost -> Connect for Windows

- Source/BLE.Client/BLE.Client.Maui/App.xaml.cs
- Source/BLE.Client/BLE.Client.Maui/AppShell.xaml
- Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj
- Source/BLE.Client/BLE.Client.Maui/Platforms/Android/AndroidManifest.xml
- Source/BLE.Client/BLE.Client.Maui/Platforms/Android/Resources/values/colors.xml
- Source/BLE.Client/BLE.Client.Maui/Resources/AppIcon/appicon.svg
- Source/BLE.Client/BLE.Client.Maui/Resources/AppIcon/appiconfg.svg
- Source/BLE.Client/BLE.Client.Maui/Resources/Splash/splash.svg
- Source/BLE.Client/BLE.Client.Maui/Resources/Styles/Colors.xaml
- Source/BLE.Client/BLE.Client.Maui/Services/LogService.cs
- Source/BLE.Client/BLE.Client.Maui/ViewModels/BLEDeviceViewModel.cs
- Source/BLE.Client/BLE.Client.Maui/ViewModels/BLEScannerViewModel.cs
- Source/BLE.Client/BLE.Client.Maui/ViewModels/BaseViewModel.cs
- Source/BLE.Client/BLE.Client.Maui/ViewModels/LogViewModel.cs
- Source/BLE.Client/BLE.Client.Maui/Views/BLEScanner.xaml
- Source/BLE.Client/BLE.Client.Maui/Views/LogViewer.xaml
- Source/BLE.Client/BLE.Client.Maui/Views/LogViewer.xaml.cs
After testing the MAUI demo application on my mobile device (Sony XQ-DQ54 - Android14) and on my Windows11 PC it seemed to fall short in several areas:
* Doesn't fit on screen.
* Log Messages non-functional
* Default App Icon
This PR addressed those initial points and tidied up some obsolete code from the view models.
A subsequent branch/PR will look into adding Connecting to a device and reading out the services/characteristics from it.
Tested with .Net-8 and Android33/34 and Windows 10 & 11 only.
> Maui client update

- Source/MvvmCross.Plugins.BLE/MvvmCross.Plugins.BLE.csproj
- Source/Plugin.BLE/Plugin.BLE.csproj
... in order to fix GHA build failures (.NET 7 is out of support by now).
> Remove net7.0 targets

- Source/Plugin.BLE/Android/BleImplementation.cs
- Source/Plugin.BLE/Apple/Adapter.cs
- Source/Plugin.BLE/Shared/AdapterBase.cs
- Source/Plugin.BLE/Shared/Contracts/IAdapter.cs
- Source/Plugin.BLE/Shared/Contracts/IDevice.cs
I hope this should fix #957 and #882.
@juniorsaraviao @jspfister-sep Could you test if this fixes the problem for you? There is a nupkg built via GitHub Actions that you can use ...
> Clear all cached devices when Bluetooth is turned off
